### ISSUE TITLE
Video resolution/quality is lower than the camera capability 

### ISSUE THREAD

**Issue by OmarSayedMostafa** [jeeliz/jeelizGlassesVTOWidget#14]
Hey, is there a way to enhance the video quality which is loaded zoomed in,  and stretchered out, so it loose some quality! is there any way to control that ? thanks !

**Comment by xavierjs** [comment]
Hi,

I have added a method to control the media constraints (cf https://github.com/jeeliz/jeelizGlassesVTOWidget/blob/master/doc.pdf ).

Then you have to set the correct canvas resolution and CSS size.
We can also provide integration services.

Best
