### ISSUE TITLE
worst then before entirely not working

### ISSUE THREAD

**Issue by alianjum351** [jeeliz/jeelizGlassesVTOWidget#16]
i posted yesterday about the invalid SKU exception but now its not working even a bit... not asking about the permission of webcam. nothing is happening. tried different browser's mozilla, chrome even UC browser. and also tired different laptops still no luck.

 image is attached.

![image](https://user-images.githubusercontent.com/52940491/61387438-8e439080-a8cf-11e9-8f92-99bba4e243d2.png)

**Comment by xavierjs** [comment]
You have to deploy your app using a http server, not open the file directly.

**Comment by alianjum351** [comment]
it was working before by directly opening...

**Comment by alianjum351** [comment]
i have to upload on a server to run this now?

**Comment by alianjum351** [comment]
it was working absolutely fine by directly opening the file... something is not right... is it working on your end?

**Comment by xavierjs** [comment]
If you are using the distant version of JeelizNNCwidget.js there was an error which has been corrected. The cache of the server has been just renewed. Then I cannot do a lot of stuffs with such poor information...

**Comment by alianjum351** [comment]
i just downloaded....and checked it on UC browser and it is working but it was not working with chrome until i refreshed the cache by pressing control+shift+R 
 
wroking fine with UC browser and with chrome

![image](https://user-images.githubusercontent.com/52940491/61394534-c56c6e80-a8dc-11e9-906e-a7d116016de5.png)
