### ISSUE TITLE
does this work on mobile browser?

### ISSUE THREAD

**Issue by alianjum351** [jeeliz/jeelizGlassesVTOWidget#18]
can this be able to work in mobile browser?

**Comment by xavierjs** [comment]
Sure man! But it also depends on the browser.

**Comment by AMINDRH91** [comment]
hi @xavierjs 
I have problem for try on WebView in ReactNative 
I tested this Link  `https://jeeliz.com/demos/faceFilter/demos/threejs/VTO/` in WebVeiw in ReactNative App before that i `get Permissions Camera ` everything work is very well BUT
When I Lunch on my Server Not Work this link `http://supernovada.com`
plz Help

**Comment by xavierjs** [comment]
Hi,

Webview are crap on IOS, they don't allow use of webcam. I don't have any workaround except releasing webapps.

Best,
Xavier

**Comment by AMINDRH91** [comment]
Now I'm Implementation with WebView in `RN`
And it works on Android `9,8,7` but not on the lower `not work on 6` ,...

Thanks for guiding me on how to run  `RN(reactnative)`
@xavierjs

**Comment by xavierjs** [comment]
On Android it may work but not on IOS.
On IOS maybe you can use a `SFSafariViewController` component, they enabled webcam access on latest IOS version (13).

**Comment by AMINDRH91** [comment]
@xavierjs What property did you use for the demo at this link?
`https://jeeliz.com/demos/faceFilter/demos/threejs/VTO/`
That runs on 9,8,7,6,5,4 Android
BUT
We use the same code that you put in `https://github.com/jeeliz/jeelizGlassesVTOWidget`   but it only works well on 9.8.7 Android, it doesn't work on 5,6  Android

**Comment by xavierjs** [comment]
Hi,

Android 5,6,4 are obsolete, so it does not matter for us if it does not work with these OS.
The first demo is using jeelizFaceFilter and THREE.js whereas the second is using our custom VTO solution including a 3D engine.

Best,
Xavier

**Comment by AMINDRH91** [comment]
<img width="1280" alt="Screen Shot 2019-09-21 at 12 23 15 AM" src="https://user-images.githubusercontent.com/33101099/65359828-5f66d500-dc06-11e9-977a-45d7c7114a87.png">
Are you  Sure Android 5,6,4 are obsolete??????????? :))) @xavierjs

**Comment by xavierjs** [comment]
**BREAKING NEWS**: Camera access is enabled on IOS14.3 which is released this Monday ( December 14th ). So Jeeliz VTO widget will work on Chrome, Firefox, Opera for IOS, and into `WKWebviews` embedded in native apps.
