### ISSUE TITLE
Integrate with android app

### ISSUE THREAD

**Issue by AsadMansoor1** [jeeliz/jeelizGlassesVTOWidget#20]
How to integrate this VTO Widget with android app. I am wondering if this is possible. I am following
[this](https://jeeliz.com/blog/how-to-use-the-jeeliz-vto-widget-in-your-everyday-projects/) tutorial.
I have completely followed the instructions but app is not running whether an issue occured i.e given below
 "Installation did not succeed.
The application could not be installed: SHELL_UNRESPONSIVE
The device timed out while trying to install the application."

what would be the pathway. Have you explained it anywhere for android integration.

**Comment by xavierjs** [comment]
It is better to do a webapp rather than a native app that nobody will install.

**Comment by AsadMansoor1** [comment]
Means this library will not work for android apps? But their is written that it would work using Mobile web?

**Comment by xavierjs** [comment]
A web app is an app that you can share with 1 link. It is written with web languages: HTML, JavaScript, Css, ...
An "Android app" is compiled and you need to download and install it.
This is designed for web app. I think it is doable to make it work as native app (android, iOS), but it is outside the scope of this github repo.

**Comment by AsadMansoor1** [comment]
Ook Understood. Do you have any tutorial or helping material that explains
it for Android app ? If not for Android then for IOS?

Regards
Asad Mehmood

**Comment by xavierjs** [comment]
This library, webojis: https://github.com/jeeliz/jeelizWeboji
has been ported to an iOS app with Cordova.
The problem is similar.
More info here: https://github.com/jeeliz/jeelizWeboji/tree/master/demos/cordova/raccoon
It works on iOS, and it should work on Android too.
But it is a kind of tinkering, IMHO it is better to keep it web.
If you want the app to be installable and have an icon on the mobile desktop you should take a loot to progressive web apps (PWA).

**Comment by AsadMansoor1** [comment]
Thanks Bourry Xavier!

 For your generous explanations! I will try it for android but after
learning IOS and analyzing its working in IOS. Is there any other library
available that will easily work for android? Work similar to Jeeliz upto
some extent??
It would be helpfull for me to complete my FYP. Waiting for your kind
response!

Thanks & Regards
Asad Mehmood
