### ISSUE TITLE
100% GPU Usage on AMD Vega 64

### ISSUE THREAD

**Issue by mikhail-karan** [jeeliz/jeelizGlassesVTOWidget#22]
Hi, having a weird issue with just your regular demo.html file. When I open it, it works fine but my GPU fan spins up and the GPU itself starts having massive coil whine because it is being pushed to 100% usage for the duration of the demo. (see image below)

![image](https://user-images.githubusercontent.com/8340258/79616165-5c679080-80d2-11ea-8322-63f54e835a59.png)

Just wondering if this is a known issue?

**Comment by xavierjs** [comment]
it is normal, this library requires some computing power to detect your face and proceed to the rendering.
