### ISSUE TITLE
How to add new glasses model to database

### ISSUE THREAD

**Issue by haiktqd** [jeeliz/jeelizGlassesVTOWidget#3]
Hi Jeeliz,

How can I add new glasses model to database. Or how can I host database on my server.

Thanks!

**Comment by xavierjs** [comment]
Hi,

This is not possible, this is a service we monetize.  You can ask for more detailed informations here: https://jeeliz.com/contact-us/ or directly at contact__at__jeeliz__dot__com.

If you want to do a VTO solution with your own 3D assets you can do it with Jeeliz Facefilter: https://github.com/jeeliz/jeelizFaceFilter and start with the miel pops demo for example. But:
- you won't have server-side fallback for users who are not compatible with WebGL,
- you won't have light reconstruction,
- it will be less optimized (workflow not 100%GPU, THREE.JS is heavier than the 3D engine used for this repo),
- you should implement raytraced shadows, PBR rendering, ... 

In this issue I explain other reasons why the project is not fully open source, especially for the assets workflow : https://github.com/jeeliz/jeelizGlassesVTOWidget/issues/2

Best regards

**Comment by trahmadeffendi** [comment]
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="content-language" content="en-EN" />

    <title>JEELIZ FACE FILTER : MIEL POPS</title>
    <title>JEELIZ FACE FILTER: MIEL POPS</title>

    
    <script src="../../../dist/jeelizFaceFilter.js"></script>
    
    <script src="../../../libs/threejs/v97/three.min.js"></script>
    
    <script src="../../../helpers/JeelizResizer.js"></script>
    
    <script src="../../../helpers/JeelizThreejsHelper.js"></script>
    
    <script src="./demo.js"></script>
    
    <script src="../../../libs/tween/v16_3_5/Tween.min.js"></script>
    
    <script src='../../../helpers/addDragEventListener.js'></script>
    
    <script src="../../appearance/widget.js"></script>
    <link rel="stylesheet" href="../../appearance/style.css" type="text/css" />
  </head>
  
  <body onload="main()" style='color: white'>
    <canvas width="600" height="600" id='jeeFaceFilterCanvas'></canvas>
  </body>
</html>

saya sudah download file nya, tpi begitu saya mencoba mils pop, saya tidak bisa membuka camera webcam saya, tolong perbaiki, dan beri saya saran secepat mungkin

**Comment by Saad-Faleh-Al-Dosri** [comment]
tried contacting you in many ways and through the link you shared. didn't work. can you make sure that contact us page is working ?

**Comment by xavierjs** [comment]
**BREAKING NEWS: YOU CAN NOW ADD YOUR OWN 3D GLASSES MODEL FROM GLTF**

More information here: https://github.com/jeeliz/jeelizGlassesVTOWidget#glasses-3d-models

**Comment by mahdiyar-oraei** [comment]
I have accessed the Glasses 3D Studio in the past without any issues, but currently, when I try to access it, I’m being asked to log in. Could you please guide me on how to regain access?

**Comment by xavierjs** [comment]
Hello,
It is not available for free anymore. Please contact-us at contact__at__jeeliz.com to know more about our pricing. You also need a commercial software license to use this software in a publicly released website, app or device (https://github.com/jeeliz/jeelizGlassesVTOWidget/blob/master/LICENSE )
