### ISSUE TITLE
is JEEWIDGET.loadStandalone still exist or deprecated ?

### ISSUE THREAD

**Issue by AjiNugroho** [jeeliz/jeelizGlassesVTOWidget#32]
Dear Jeeliz

the documentations say that we can add our 3d assest, using JEEWIDGET.loadStandalone 

JEEWIDGET.load_modelStandalone(exportedGlassesModel,function(){console.log('INFO: EXPORTED MODEL LOADED');})

is the function deprecated or not ?

**Comment by xavierjs** [comment]
Read the doc: https://github.com/jeeliz/jeelizGlassesVTOWidget#as-a-static-file
https://jeeliz.com/glassesStudio3D/doc/GlassesStudio3DDoc.pdf

I have written nowhere that it is a deprecated function.
If you need specific help about adding your own 3D models we charge for that, please contact us by email.
