### ISSUE TITLE
3D Glasses Json Example not working

### ISSUE THREAD

**Issue by sprengerst** [jeeliz/jeelizGlassesVTOWidget#33]
Hello,

your 3D Glasses JSON example is not working.

After loading the exported JSON object with:
        
     JEEWIDGET.load_modelStandalone(actual_JSON);
        
It returns a:

      Uncaught TypeError: Cannot read property 'length' of null

      
I know that you don't give support for free, but your demo is broken here.

Best,
Stefan

**Comment by sprengerst** [comment]
https://gist.github.com/sprengerst/dde6db54268af50ee89aba2da2027682

**Comment by xavierjs** [comment]
Hi,

Good catch, I have fixed a bug in Glasses Studio 3D with texture exportation and another one in the widget.
I have added 2 models exported using Glasses Studio 3D in this repository, here: https://github.com/jeeliz/jeelizGlassesVTOWidget/tree/master/glasses3D

And I have updated the demo.html, when you click on "Model 3" it now loads `glasses1.json`
