### ISSUE TITLE
How to change camera after initialization?

### ISSUE THREAD

**Issue by derekmtran** [jeeliz/jeelizGlassesVTOWidget#34]
I have UI to allow the user to pick which camera they have after the VTO has been started. I see in the documentation that you can set it at initialization but nothing on how to do it after that. The alternative would be to destroy/deinit the library and then reinitialize it, but it looks like there is no destroy() method like there is in the other Jeeliz libs.

How can I set deviceId after initialization has already occurred?

**Comment by derekmtran** [comment]
Just following up. What's the best approach to either destroy and restart or change device input while the app is already running?

**Comment by xavierjs** [comment]
Hi,

A `destroy()` method have been implemented, but it is currently not possible to switch the device ID after initialization.
By default, the requested camera has video constraint `facingMode: user`, so it should pick the right camera

**Comment by SyedAzeemJaved** [comment]
How do you change it at initialization? I see no such thing in the documentation, am I missing something?
