### ISSUE TITLE
Integrate with DotNet MVC  C# in Visual Studio 2019

### ISSUE THREAD

**Issue by kwiksys** [jeeliz/jeelizGlassesVTOWidget#36]
I have added the widget in the DotNet MVC framework.
It worked fine in Firefox and Safari but not Chrome.
Reason it is because it cannot detect the camera in Chrome.
Error message  errlable = FALLBACK_UNAVAILABLE
Tried to find further error detail but could not

Appreciate if you can check on this. Thanks

**Comment by xavierjs** [comment]
Hi,

Does the bug still occur? I have added various bug fixes since last January.
Without sharing your code, I can do nothing for you.
Please send a pull request to this Github repository with your integration. Some other users may be interested in it.
