### ISSUE TITLE
Capture image

### ISSUE THREAD

**Issue by aberth** [jeeliz/jeelizGlassesVTOWidget#37]
I'm trying to put a Capture Image button into the VTO Canvas.
When I call the function JEEWIDGET.capture_image(15, captured(), false); I get this error in console:
'ma is not a function' from the file JeelizNNCwidget.js

(captured() is my function callback).

**Comment by xavierjs** [comment]
Hi,

Does this error still occur with the latest version of the widget? I have pushed various fixes these later weeks.
Please note that the API has been renamed to `JEELIZVTOWIDGET`
