### ISSUE TITLE
How to add my own 3d models of glass or earring

### ISSUE THREAD

**Issue by enemali** [jeeliz/jeelizGlassesVTOWidget#4]
is there any way i can add my own 3d models?

**Comment by xavierjs** [comment]
Take a look at other submitted issues before submitting a new one plz, you will quickly find the answer :)

**Comment by enemali** [comment]
sorry about that

**Comment by xavierjs** [comment]
No problem :)

**Comment by xavierjs** [comment]
duplicate of #3
