### ISSUE TITLE
Change Env-Map Image

### ISSUE THREAD

**Issue by chrisslazzz** [jeeliz/jeelizGlassesVTOWidget#41]
Is there a possibility to change the environment map image? Or are you planning on adding this feature in the future?

Appart from that, I really like the widget! Thanks a lot for your work and sorry that I have misused this bug report as a feature request form.

**Comment by xavierjs** [comment]
Hi,

This feature is not available. Indeed, the current envmap is generated dynamically from:
* an ambient light depending on the output of the neural network (to reproduce ambient lighting)
* a directional light also depending on the output of the neural network (both direction and intensity), to reproduce the directional lighting
* a background image
* a screen placeholder
* a background image where lights only are spotted and with a lighting coefficient

So the lighting is not very straightforward to set.
