### ISSUE TITLE
Adding hand model for virtual button but require calling of video feed function 

### ISSUE THREAD

**Issue by jhng83** [jeeliz/jeelizGlassesVTOWidget#45]
Hello,

I am trying to incorporate Mediapipe hand model with the widget to have some kind of virtual button (instead of clicking using mouse) on the button to select frame. However, I realize the webcam is activated upon activating the widget which prevent me from utilizing the webcam for hand recognition. I realize the activation of the webcam is built in with the "JEELIZVTOWIDGET.start" function, which prevent from calling the video feed for Mediapipe. I was wondering there could be a feature to call the video feed seperately?

Thanks!
JH

**Comment by xavierjs** [comment]
Hi,

Sorry for my long delay to answer, I did not get a Github notification I don't know why.
Jeeliz VTO widget is not compatible with Mediapipe. The mediapipe hand detection and tracking model already uses a log of resources and it won't be reasonable to run Jeeliz VTO simultaneously.
