### ISSUE TITLE
`Qa.switch_sleep` is not a function

### ISSUE THREAD

**Issue by Lucaslpena** [jeeliz/jeelizGlassesVTOWidget#46]
Running into an error: `Qa.switch_sleep` is not a function.
I have added the relevant package, and file into my project.

**Comment by ismailajizou** [comment]
I have the same issue, have you found the solution?

**Comment by ismailajizou** [comment]
Thanks for your answer I have tried to remove react strict mode and it worked fine

**Comment by xavierjs** [comment]
Hi,

Sorry for my long delay to answer, I did not received a Github notification for this issue.
Is the error still occurring? I have pushed some updates since then so I hope it is fixed.
