### ISSUE TITLE
 can i stick on the upload photo ?

### ISSUE THREAD

**Issue by heiheiheibj** [jeeliz/jeelizGlassesVTOWidget#47]
I'd like to check if the sunglass can stick on the upload photo to instead of the vedio modle? Thanks.

**Comment by ratheeshkpattambi** [comment]
@xavierjs really appreciate  if you can provide an example or point to the code - how can we how can we upload photo instead of video.

**Comment by xavierjs** [comment]
Hi,
Jeeliz provides a high-quality, real-time experience. Photo-based VTO is cheap and we prefer not to release this kind of cheap experience under our brand.
