### ISSUE TITLE
Failed to run load_modelStandalone

### ISSUE THREAD

**Issue by xielong** [jeeliz/jeelizGlassesVTOWidget#50]
When I click on Model 3, an error message appears：

<img width="479" alt="截屏2023-03-04 23 32 55" src="https://user-images.githubusercontent.com/3864413/222915039-454dae7c-b33b-41ff-8cd3-79c1dabfdf43.png">

**Comment by xavierjs** [comment]
Hi dude
Are you running the latest version of Jeeliz VTO widget? I retested the deployed demo here: https://jeeliz.com/demos/jeelizWidgetGitPublicDemo/
And it works when I click on model3

**Comment by xielong** [comment]
Yes, I just downloaded the latest version again and still encountered the same common issue. 
I opened the website  you provided and it was working fine as well.
