### ISSUE TITLE
Plugin stuck in Loading

### ISSUE THREAD

**Issue by janmichaelvega** [jeeliz/jeelizGlassesVTOWidget#51]
Using Squarespace. Website seems to be recognizing both the css and the html.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/131467618/233683409-11582ecc-4f7c-4ef5-9c4d-e2c7f0a2b8b5.png">

**Comment by xavierjs** [comment]
Hi @janmichaelvega 

It seems to be a Squarespace-related issue. I would be glad to provide integration support, please choose a plan first on https://jeeliz.com/#pricing
