### ISSUE TITLE
Prevent the library from searching a webcam

### ISSUE THREAD

**Issue by ismailajizou** [jeeliz/jeelizGlassesVTOWidget#57]
I want to use this library with CCTV but after I managed to do it the I figured out that the library searches for webcam by default, if not attached it gives an error and doesn't call onWebcamGet method where I change the stream with the CCTV stream.
Is it possible to call onWebcamGet even when webcam not attached or add a feature to disable that behaviour.

**Comment by xavierjs** [comment]
Hi @ismailajizou 

With the latest version, you can disable camera request by adding among the `JEELIZVTOWIDGET.start` options `isRequestCamera: false`.
Then it will request the camera video stream and start the VTO session when you will run `JEELIZVTOWIDGET.request_cameraVideoStream()`

Please note that to use this library for a commercial project you need to get a commercial software license, even if it is for kiosk use.

**Comment by ismailajizou** [comment]
It still gives an error after calling `JEELIZVTOWIDGET.request_cameraVideoStream()`  to show the video stream because no webcam is attached.
Is there a way to call `onWebcamGet` without the camera being attached?

**Comment by xavierjs** [comment]
Hi @ismailajizou 
Please contact me at contact@jeeliz.com and provide more details about your project for the software license, and share your code with me on a private repo so that I can take a look.
