### ISSUE TITLE
How did you stop zooming in on ios safari?

### ISSUE THREAD

**Issue by whilemouse** [jeeliz/jeelizGlassesVTOWidget#6]
Hi. I use your jeeliz face filter very well.
I'm sorry. I have a question that is not related to your project.

When playing the VTO demo, I saw that the video canvas could not zoom in and out.
If you do not mind, can you tell me what you did?

**Comment by xavierjs** [comment]
Hi,

I don't understand what is the problem exactly.
What do you mean about zooming the video canvas ? Is is a video resolution problem or a canvas resolution problem ?
