### ISSUE TITLE
Don't work on Google Chrome.

### ISSUE THREAD

**Issue by Hamid-Nazir** [jeeliz/jeelizGlassesVTOWidget#7]
Whenever I run your given demo-virtual try on program error occur. Pleasem have a look and help me out asap.
Thanks
![jeeliz1](https://user-images.githubusercontent.com/47783326/53020863-b0002f00-3479-11e9-9f7c-5118b2ff77ea.PNG)
![jeeliz](https://user-images.githubusercontent.com/47783326/53020864-b0002f00-3479-11e9-85b7-1283743fb5c9.PNG)

**Comment by xavierjs** [comment]
Hi,

We are very sorry, some services crashed at 5:00am Paris time this morning on our server.
A silly out of memory error which has been corrected 10 minutes ago.
So the glasses database server was not available.
It should work now :)

Best,
Xavier

**Comment by Hamid-Nazir** [comment]
It's working.
Thanks Xavier
