### ISSUE TITLE
"try on a picture" button not working

### ISSUE THREAD

**Issue by vikssin17** [jeeliz/jeelizGlassesVTOWidget#8]
after clicking on "try on a picture"  and choose photo from the files and after uploading its not loading in canvas and after 2-3 mins it logs error in console "Access to XMLHttpRequest at 'https://fallbackglassesdb.jeeliz.com/' from origin 'https://jeeliz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

Please find the attached screenshots.
![screen shot 2019-02-26 at 7 10 22 pm](https://user-images.githubusercontent.com/23048138/53416806-3ed0f680-39fa-11e9-9f79-275b5557c64d.png)
![screen shot 2019-02-26 at 7 10 25 pm](https://user-images.githubusercontent.com/23048138/53416821-45f80480-39fa-11e9-9ff5-0498bc4e9285.png)

**Comment by xavierjs** [comment]
Hi,
Thank you for this detailed bug report.
Aftern 231 days running without interruption, the rendering server had crashed so I restarted it, it should work now :) .
Best,
Xavier

**Comment by vikssin17** [comment]
[image: Screen Shot 2019-02-27 at 11.23.14 AM.png]

Thank you so much Sir
Its working fine now but its not detected eye properly on some of the
uploaded photos. Below is the uploaded picture and its also cut my photo
from upwards too


In some photos its working fine also. Below attached: working fine with
this photo.
[image: Screen Shot 2019-02-27 at 11.30.19 AM.png]

Thanks so much for replying fast.

**Comment by xavierjs** [comment]
I don t have time for this. The fallback mode is only for loosers who have shitty smartphones.

**Comment by vikssin17** [comment]
ok no problem but thanks again for your cooperation

**Comment by vikssin17** [comment]
one more thing will it work for the uploaded video ??

Best
Vikas

**Comment by xavierjs** [comment]
Hi,

Currently no, but we can implement the feature.
We can also improve the server side fallback.
But we can only do this as a paid job.

Best,
Xavier
