### ISSUE TITLE
Is it possible to run the widget without a webcam ?

### ISSUE THREAD

**Issue by gabrielIV** [jeeliz/jeelizGlassesVTOWidget#9]
I'm getting a blank screen when working on a pc without a webcam. I was wondering if it is possible to load photos via passing base64 data ( or any other file formats ) to the api without having to use the webcam.

**Comment by xavierjs** [comment]
Hi,

This feature is currently not implemented in this Github repository.
However, @Jeeliz we would be happy to help you to adapt our libraries to fit your needs.
You can ask to our commercial team for specific development services at contact__at__jeeliz.com and we will send you a proposal. 


Best regards,
Xavier
